In [3]:
pip install -r Packages.txt

Note: you may need to restart the kernel to use updated packages.


In [4]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
import scipy.stats as stats
import seaborn as sns
from sklearn.model_selection import cross_val_score, KFold
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report
from sklearn.metrics import r2_score

In [5]:
file_path_preprocess = r'D:\Alzheimer_s dataset\brain\TMTpreprocessed_data.xlsx'

original_data = pd.read_excel(file_path_preprocess)

#copying the data to maintain the originalilty of the data
data = original_data.copy()

#Dimension of the data
print(data.shape)

#visualization of the data points
data.head()
# print(data.iloc[:, 0:2])

(118, 3701)


Unnamed: 0    Q03001    Q9UPA5    Q09666    Q9Y4G6    O15020  \
0  Banner.b01.127C  0.793794  0.797887  0.808218  0.796770  0.791914   
1  Banner.b01.129C  0.806849  0.798639  0.838980  0.807406  0.800303   
2  Banner.b01.129N  0.804411  0.810861  0.825216  0.812318  0.800979   
3  Banner.b01.130C  0.797387  0.800212  0.811385  0.807874  0.798513   
4  Banner.b02.127C  0.811064  0.800206  0.853693  0.805791  0.799589   

     Q02952    Q9Y490    Q12955    P35579  ...    P06703    P30536    P56277  \
0  0.816653  0.724105  0.758086  0.798568  ...  0.435895  0.331287  0.280285   
1  0.834854  0.733493  0.755572  0.802688  ...  0.416044  0.365588  0.311146   
2  0.824337  0.727744  0.763743  0.800215  ...  0.395066  0.336315  0.308950   
3  0.821305  0.725272  0.763010  0.799233  ...  0.400856  0.342176  0.296247   
4  0.829412  0.746777  0.761575  0.803144  ...  0.487932  0.400886  0.241778   

   age  sex   pmi  disease_group  batch   study  batch_org  
0   86    0  2.50             AD      1  Banner          1  
1   81    1  2.83             AD      1  Banner          1  
2   75    0  2.75        Control      1  Banner          1  
3   81    0  4.00             AD      1  Banner          1  
4   74    0  3.00             AD      1  Banner          2  

[5 rows x 3701 columns]

In [6]:
#features of the data
x = data.iloc[:, 1:-7]       #all the intensity values of sample with respect to the proteins

#target of the data
y = data['disease_group']   #binary data (AD/control)

x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.3, random_state=42)



Logistic regression

In [8]:
#features of the data
x = data.iloc[:, 1:-7]       #all the intensity values of sample with respect to the proteins

#target of the data
y = data['disease_group']   #binary data (AD/control)

x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=42)



model = LogisticRegression()
model.fit(x_train, y_train)

y_pred = model.predict(x_test)
accuracy = accuracy_score(y_test, y_pred)
conf_matrix = confusion_matrix(y_test, y_pred)
class_report = classification_report(y_test, y_pred)

print(f"Accuracy: {accuracy}")
print("Confusion Matrix:")
print(conf_matrix)
print("Classification Report:")
print(class_report)

print(y_pred)

Accuracy: 0.8333333333333334
Confusion Matrix:
[[20  0]
 [ 4  0]]
Classification Report:
              precision    recall  f1-score   support

          AD       0.83      1.00      0.91        20
     Control       0.00      0.00      0.00         4

    accuracy                           0.83        24
   macro avg       0.42      0.50      0.45        24
weighted avg       0.69      0.83      0.76        24

['AD' 'AD' 'AD' 'AD' 'AD' 'AD' 'AD' 'AD' 'AD' 'AD' 'AD' 'AD' 'AD' 'AD'
 'AD' 'AD' 'AD' 'AD' 'AD' 'AD' 'AD' 'AD' 'AD' 'AD']


c:\Users\Sundar Kannan\miniconda3\envs\alzheimers\Lib\site-packages\sklearn\metrics\_classification.py:1517: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
c:\Users\Sundar Kannan\miniconda3\envs\alzheimers\Lib\site-packages\sklearn\metrics\_classification.py:1517: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
c:\Users\Sundar Kannan\miniconda3\envs\alzheimers\Lib\site-packages\sklearn\metrics\_classification.py:1517: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metr

Decision tree model

In [9]:
#features of the data
x = data.iloc[:, 1:-7]       #all the intensity values of sample with respect to the proteins

#target of the data
y = data['disease_group']   #binary data (AD/control)

x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=42)


# Initialize the Decision Tree model
model = DecisionTreeClassifier()

# Train the model
model.fit(x_train, y_train)

# Predict on the test set
y_pred = model.predict(x_test)

# Evaluate the model
accuracy = accuracy_score(y_test, y_pred)
conf_matrix = confusion_matrix(y_test, y_pred)
class_report = classification_report(y_test, y_pred)

print(f"Accuracy: {accuracy}")
print("Confusion Matrix:")
print(conf_matrix)
print("Classification Report:")
print(class_report)

print(y_pred)


Accuracy: 0.9166666666666666
Confusion Matrix:
[[19  1]
 [ 1  3]]
Classification Report:
              precision    recall  f1-score   support

          AD       0.95      0.95      0.95        20
     Control       0.75      0.75      0.75         4

    accuracy                           0.92        24
   macro avg       0.85      0.85      0.85        24
weighted avg       0.92      0.92      0.92        24

['AD' 'Control' 'AD' 'Control' 'AD' 'AD' 'AD' 'AD' 'AD' 'AD' 'AD' 'AD'
 'Control' 'AD' 'AD' 'AD' 'AD' 'Control' 'AD' 'AD' 'AD' 'AD' 'AD' 'AD']


Random Forest model

In [18]:
#features of the data
x = data.iloc[:, 1:-7]       #all the intensity values of sample with respect to the proteins

#target of the data
y = data['disease_group']   #binary data (AD/control)

x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.3, random_state=42)


# Initialize the Random Forest model
model = RandomForestClassifier(n_estimators=100, random_state=42)

# Train the model
model.fit(x_train, y_train)

# Predict on the test set
y_pred = model.predict(x_test)

# Evaluate the model
accuracy = accuracy_score(y_test, y_pred)
conf_matrix = confusion_matrix(y_test, y_pred)
class_report = classification_report(y_test, y_pred)

print(f"Accuracy: {accuracy}")
print("Confusion Matrix:")
print(conf_matrix)
print("Classification Report:")
print(class_report)

Accuracy: 0.7777777777777778
Confusion Matrix:
[[28  0]
 [ 8  0]]
Classification Report:
              precision    recall  f1-score   support

          AD       0.78      1.00      0.88        28
     Control       0.00      0.00      0.00         8

    accuracy                           0.78        36
   macro avg       0.39      0.50      0.44        36
weighted avg       0.60      0.78      0.68        36



c:\Users\Sundar Kannan\miniconda3\envs\alzheimers\Lib\site-packages\sklearn\metrics\_classification.py:1517: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
c:\Users\Sundar Kannan\miniconda3\envs\alzheimers\Lib\site-packages\sklearn\metrics\_classification.py:1517: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
c:\Users\Sundar Kannan\miniconda3\envs\alzheimers\Lib\site-packages\sklearn\metrics\_classification.py:1517: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metr